name: Automate creating a Github Issue 
run-name: ${{ github.actor }} is testing out GitHub Actions
permissions:
  issues: write  # Issue作成のみの権限を付与
  contents: read # リポジトリの読み取り権限
on: 
  repository_dispatch:
    types: ["error_detect"]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
        
      - name: リクエスト接続確認
      - run: echo "From payload, ${{ github.event.client_payload.message}}."
      
      - name: Issue の作成
        run: |
          cat << 'EOF' | gh issue create --label "bug" --title "Automate creating issue" --body-file -
          ## Automate creating issue

          ## Sample topic 1. 

          ## Sample topic 2. 
          - 
          EOF
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      
