name: Testing Claude via GitHub Actions

on: 
  repository_dispatch:
    types: ["error_detect"]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow read access to the repository
      issues: write  # Allow only issue creation
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check request connection
        run: echo "From payload message, '${{ github.event.client_payload.message}}'."
      
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          prompt: |
            # Analyze the following error message and make an issue then suggest the cause of the problem and a solution. 
            ${{ github.event.client_payload.message}}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --max-turns 10
            --mcp-config .github/mcp-servers.json"

          # Optional: Advanced settings configuration
          # settings: |
          #   {
          #     "env": {
          #       "NODE_ENV": "test"
          #     }
          #   }
      # - name: Issue の作成
      #   run: |
      #     cat << 'EOF' | gh issue create --label "bug" --title "Automate issue creation" --body-file -
      #     ## Automate issue creation

      #     ## Sample topic 1. 

      #     ## Sample topic 2. 
      #     - 
      #     EOF
      #   env:
      #     GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      
